# Generated by Django 5.2.3 on 2025-06-16 19:49
# Permite que a pasta migrations seja reconhecida como um  pacote Python.Guarda
# o histórico de mudanças no banco de dados.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('vendas', models.FloatField(verbose_name='Total de Vendas')),
                ('meta', models.FloatField(verbose_name='Meta do Mês')),
            ],
        ),
    ]
